steps:  
  - label: "Docker Login"
    command: ".buildkite/run_build.sh"
    plugins:
      - docker-login#v2.0.1:
          username: 8484810020
          password-env: DOCKER_HUB_PASSWORD
  - name: ":node:"
    command: npm test
    plugins:
      - docker-compose#v3.9.0:
          run: app
