env:
  DOCKER_HUB_PASSWORD: "bunty@123"
  
steps:
  - input: ":rocket: Infra Action"
    fields:
      - select: "Terraform apply/destroy?"
        key: "ACTION"
        options:
          - label: "Destroy"
            value: "destroy"
          - label: "Deploy"
            value: "apply"

  - label: ":terraform:" 
    commands: |
      cd ecs
      terraform init
      terraform validate
      terraform plan 
      terraform apply -auto-approve
    artifact_paths:
      - "ecs/*"
    concurrency: 1
    concurrency_group: ecs

  - label: ":docker:"
    command: "./.buildkite/run_build.sh"
    plugins:
      - docker-login#v2.0.1:
          username: 8484810020
          password-env: DOCKER_HUB_PASSWORD

  
  - name: ":node:"
    command: npm test
    plugins:
      - docker-compose#v3.9.0:
          run: app

  - label: "ImgVersion"
    command: "./version.sh"

  - label: ":ecr:"
    plugins:
      - seek-oss/docker-ecr-publish#v2.4.0:
          ecr-name: nodeapp
          account-id: 433375820816 
          region: ap-south-1
          image: 433375820816.dkr.ecr.ap-south-1.amazonaws.com/nodeapp:$BUILDKITE_BUILD_NUMBER


  - label: ":dockerhub:"
    commands: |
      docker push 433375820816.dkr.ecr.ap-south-1.amazonaws.com/nodeapp:$BUILDKITE_BUILD_NUMBER
      docker rmi $(docker images -aq)